
# main config
auto: false
server: false
lsi: false
exclude: shared
permalink: pretty
source: _source
posts_include:
  - .textile
  - .markdown
api: true
url: 'http://localhost:4567'
language: en-US

keys:
  google_analytics: "UA-15601175-7"
info:
  address:
    city: Berkeley
    state: CA
    zip: 94704
  email: "lancejpollard@gmail.com"
  website: http://ilove4d.com
  company: 4D

authors:
  -
    name: Lance Pollard
    age: 23
    city: Berkeley
    state: CA
    zip: 94704
    country: United States
    company: 4D Design Lab
    website: http://github.com/viatropos
links:
  twitter: http://www.twitter.com/viatropos
  facebook: "http://www.facebook.com/viatropos"
  github: http://www.github.com/viatropos
  stack_overflow: ""
  digg: ""
  myspace: ""
  linked_in: ""
  website: "http://www.ilove4d.com"
  google_apps: "http://www.google.com/a/ilove4d.com"
icons:
  favicon: /images/favicon.ico
  touch_icon: /images/touch-icon.jpg

metadata:
  domain: ilove4d.com
  title: SeeSaw
  tagline: "Text Beautifier, Minifier, and Convertifier"
  description: "Text Beautifier, Minifier, and Convertifier"
  author: "Lance Pollard"
  copyright: "4D | All Rights Reserved"
  country: "United States"
  classification: Techonology and Innovation
  keywords: "Pretty Printer, Code Beautifier, Javascript Beautifier, 
    CSS Beautifier, CSS Minimizer, YUI Compressor, CSS Compressor, 
    Javascript Compressor, Parsing, Text Conversion, Ruby, Sinatra, 
    HAML, Textile, Mardown, HTML, JQuery, Text Layout Framework, Sass
    Flash HTML, Flex HTML, iLove4D"